#!/bin/bash
# Apple Developer Certificate Export Script for TunnelForge CI/CD
# Run this on macOS with Keychain Access

echo "=== Apple Developer Certificate Export for TunnelForge ==="
echo ""
echo "This script provides instructions for exporting your Apple Developer ID certificate."
echo "You must run these commands on macOS with Keychain Access."
echo ""
echo "Prerequisites:"
echo "- Apple Developer Account ($99/year) ✅ YOU HAVE THIS"
echo "- macOS computer with Keychain Access"
echo "- Xcode installed (for certificate management)"
echo ""
echo "=== Step 1: Generate Developer ID Certificate ==="
echo ""
echo "1. Go to: https://developer.apple.com/account/resources/certificates/list"
echo "2. Click the '+' button to create a new certificate"
echo "3. Select 'Developer ID Application' (for distribution outside Mac App Store)"
echo "4. Follow the prompts to generate and download the certificate"
echo "5. Double-click the downloaded .cer file to install it in Keychain Access"
echo ""
echo "=== Step 2: Verify Certificate in Keychain ==="
echo ""
echo "Run this command in Terminal on macOS:"
echo ""
echo "security find-identity -v -p codesigning"
echo ""
echo "You should see something like:"
echo "'Developer ID Application: Your Name (TEAM_ID)'"
echo ""
echo "=== Step 3: Export Certificate for CI/CD ==="
echo ""
echo "Run these commands in Terminal on macOS:"
echo ""
echo "# Export the certificate as .p12 format"
echo "security export -k ~/Library/Keychains/login.keychain-db \\"
echo "  -t certs \\"
echo "  -o ~/Desktop/DeveloperIDApplication.p12 \\"
echo "  -P"
echo ""
echo "# Convert to base64 for GitHub secret"
echo "base64 -i ~/Desktop/DeveloperIDApplication.p12 | pbcopy"
echo ""
echo "=== Step 4: Get Required Information ==="
echo ""
echo "# Team ID (from Apple Developer Portal)"
echo "Visit: https://developer.apple.com/account"
echo "Go to: Membership → Team ID (copy the 10-character code)"
echo ""
echo "# Apple ID"
echo "Your Apple Developer Account email address"
echo ""
echo "# App-Specific Password for notarization"
echo "Visit: https://appleid.apple.com/account/manage"
echo "Security → App-Specific Passwords → Generate"
echo "Name it: 'TunnelForge CI/CD'"
echo "Copy the generated password (format: xxxx-xxxx-xxxx-xxxx)"
echo ""
echo "=== Step 5: GitHub Secrets to Set ==="
echo ""
echo "After running the export commands above, set these GitHub secrets:"
echo ""
echo "MACOS_DEVELOPER_CERT:     [paste base64 content from pbcopy]"
echo "MACOS_CERT_PASSWORD:      [password you set in step 3]"
echo "MACOS_DEVELOPER_ID:       [from certificate name]"
echo "MACOS_TEAM_ID:            [10-character team ID from portal]"
echo "MACOS_APPLE_ID:           [your Apple ID email]"
echo "MACOS_APP_PASSWORD:       [app-specific password]"
echo "MACOS_KEYCHAIN_PASSWORD:  [choose a secure random password]"
echo ""
echo "=== Verification ==="
echo ""
echo "Test that everything works:"
echo ""
echo "gh secret list | grep MACOS"
echo ""
echo "You should see 7 MACOS_* secrets listed."
echo ""
echo "=== Next Steps ==="
echo ""
echo "Once secrets are set:"
echo "1. Run: gh workflow run build-macos.yml -f sign_artifacts=true"
echo "2. Monitor the build at: https://github.com/YOUR_USERNAME/tunnelforge/actions"
echo "3. Download signed .dmg and .app files from artifacts"
echo ""
echo "=== Troubleshooting ==="
echo ""
echo "If notarization fails:"
echo "- Verify app-specific password is correct"
echo "- Check Team ID matches certificate"
echo "- Ensure MACOS_APPLE_ID is correct"
echo ""
echo "Docs: https://developer.apple.com/support/code-signing/"
echo ""
echo "=== END OF INSTRUCTIONS ==="