version: '3.8'

services:
  vibetunnel-npm-beta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibetunnel-npm-beta-test
    environment:
      - NODE_ENV=development
      - VIBETUNNEL_NO_AUTH=true
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./public:/app/public
      # Exclude node_modules
      - /app/node_modules
      - /app/node-pty/node_modules
    ports:
      - "4021:4020"
    command: pnpm run dev