name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  swift:
    name: Swift CI
    uses: ./.github/workflows/swift.yml
    
  rust:
    name: Rust CI
    uses: ./.github/workflows/rust.yml
    
  node:
    name: Node.js CI
    uses: ./.github/workflows/node.yml