name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  node:
    name: Node.js CI
    uses: ./.github/workflows/node.yml

  mac:
    name: Mac CI
    needs: node
    uses: ./.github/workflows/mac.yml
    
  ios:
    name: iOS CI
    needs: node
    uses: ./.github/workflows/ios.yml