name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Install SwiftFormat  
      run: brew install swiftformat
      
    - name: Run SwiftFormat
      run: swiftformat . --lint
      
    - name: Run SwiftLint
      run: swiftlint